### Get all articles

get http://localhost:3000/articles
Content-Type: application/json

### Create Article
post http://localhost:3000/articles
Content-Type: application/json

{
  "title": "blablabla",
  "body": "chest high and clean"
}
